[custom.all.idris2-vega]
type = "local"
path = "."
ipkg = "idris2-vega.ipkg"
test = "test/test.ipkg"

[custom.all.idris2-vega-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.json-schema]
type = "github"
url = "https://github.com/madman-bob/idris2-json-schema"
ipkg = "json-schema.ipkg"
commit = "latest:main"
